CREATE TABLE IF NOT EXISTS "work_type" (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  doc_type VARCHAR(2),
  unit_id INTEGER,
  active_from TIMESTAMP NOT NULL,
  active_to TIMESTAMP NOT NULL,
  remarks VARCHAR(255),
  cgst DECIMAL(5, 4),
  sgst DECIMAL(5, 4),
  igst DECIMAL(5, 4),
  hsn_code VARCHAR(10),
  hsn_desc VARCHAR(255),
  clause BOOLEAN DEFAULT TRUE NOT NULL,
  rev_type INTEGER,
  hrs_applicable BOOLEAN DEFAULT FALSE NOT NULL,
  component_for INTEGER,
  invoice_for VARCHAR(20),
  active BOOLEAN DEFAULT TRUE,
  added_by INTEGER NOT NULL,
  add_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_by INTEGER,
  update_date TIMESTAMP,


  FOREIGN KEY (unit_id) REFERENCES common_master (id),
  FOREIGN KEY (rev_type) REFERENCES common_master (id),
  FOREIGN KEY (component_for) REFERENCES common_master (id),
  FOREIGN KEY (added_by) REFERENCES users (id)
);